### ISSUE TITLE
Student film page: Wrong color on right hand column

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/nbr#1]
Hey @kpettinga I've noticed that the films on the right-hand column are using the wrong color coding for the various awards. It seems like it's pulling in the same color as the awarded film.

See the film A Place of Spirit. Has yellow for MCG Award.

See the screen shot.
![image](https://cloud.githubusercontent.com/assets/12611145/13288595/a3acf5a4-dada-11e5-81b1-c94fbc7b6999.png)

**Comment by kpettinga** [comment]
Oh right, saw that too. Just forgot to push the fix.
