### ISSUE TITLE
MCG Award landing page order of films

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/nbr#5]
@kpettinga I added all of the MCG award winning films but on the MCG award landing page some of the awards are not appearing in chronological order (most recent to past), can this be fixed?
![screen shot 2016-03-16 at 8 48 03 am](https://cloud.githubusercontent.com/assets/1680051/13812707/128124da-eb54-11e5-9e19-e66def251831.png)

**Comment by kpettinga** [comment]
@Jessdwilson goin forward, they'll need to make sure that the dates for these Student Film posts are set to the same year in which they received the award. For instance, a student film from 2013 should be published with 2013 as the year in the publish settings. I'll go thru and set the proper dates for the existing student films.
