### ISSUE TITLE
Order of awards - Student Awards landing page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/nbr#6]
@kpettinga Can we rearrange the order of awards in the header on the student awards landing page? Ideally, NBR Student Grant would be listed first, then MCG, then Senior Post then Light Iron. 

![screen shot 2016-03-16 at 11 03 10 am](https://cloud.githubusercontent.com/assets/1680051/13817497/c7b77426-eb68-11e5-86bd-872f42168ee2.png)

**Comment by Jessdwilson** [comment]
Also, on the Student Awards landing page for individual films the film awards are appearing in different orders, for instance in the attached Light Iron appears before Student Grant but Senior Post is after Student Grant... Can this be fixed so Student Grant is always first followed by the other awards? 
![screen shot 2016-03-16 at 11 21 05 am](https://cloud.githubusercontent.com/assets/1680051/13817674/76aa5c00-eb69-11e5-8609-b3f706c690ca.png)

**Comment by kpettinga** [comment]
Hey @Jessdwilson, I investigated this a bit more. We can use a plugin that will let us sort the taxonomy terms for student awards. And that sort order will work fine in areas where we list all of the student awards, namely the header of these student film pages. But when it comes to listing each film's awards in the order we specified, Wordpress can't do it. Or at least I haven't found a way after messing with it for a while. So if the client is asks, its just not technically possible at this point.

**Comment by Jessdwilson** [comment]
thanks @kpettinga for the header on the Student Awards page, can the order of the awards change to NBR Student Award, MCG, Senior Post, Light Iron? When I looked at Taxonomy and tried reordering these it didn't have an effect on the site 

![screen shot 2016-03-17 at 10 16 18 am](https://cloud.githubusercontent.com/assets/1680051/13848761/9c98f712-ec29-11e5-8ec7-3a98f67ea754.png)
